<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>com.petroxpert</groupId>
    <artifactId>petroxpert-ms</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <modules>
        <module>petroxpert-ms-contract</module>
        <module>petroxpert-ms-persistence</module>
        <module>petroxpert-ms-services</module>
        <module>petroxpert-ms-presentation</module>
        <module>petroxpert-ms-application</module>
    </modules>

    <properties>
        <java.version>21</java.version>
        <maven.compiler.release>${java.version}</maven.compiler.release>
        <spring.boot.version>3.4.5</spring.boot.version>
        <maven-compiler-plugin.version>3.13.0</maven-compiler-plugin.version>
        <maven-surefire-plugin.version>3.5.3</maven-surefire-plugin.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring.boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>com.petroxpert</groupId>
                <artifactId>petroxpert-ms-contract</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.petroxpert</groupId>
                <artifactId>petroxpert-ms-persistence</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.petroxpert</groupId>
                <artifactId>petroxpert-ms-services</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.petroxpert</groupId>
                <artifactId>petroxpert-ms-presentation</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin.version}</version>
                <configuration>
                    <release>${maven.compiler.release}</release>
                    <parameters>true</parameters>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven-surefire-plugin.version}</version>
            </plugin>
        </plugins>
    </build>
</project>
